// licenses/THIRD_PARTY_NOTICES.md and the manifest's `sources`, both generated from
// sources.lock.json so the credits can never drift from what the build actually used.

/** Problems that make a source's notice incomplete (the build refuses to ship with any). */
export function noticeProblems(lock) {
  const texts = new Set(lock.licenseTexts.map((t) => t.file))
  const problems = []
  for (const s of lock.sources) {
    for (const field of ['name', 'version', 'homepage', 'license', 'licenseUrl', 'attribution', 'notes']) {
      if (!s[field]) problems.push(`${s.id}: no ${field}`)
    }
    if (!s.licenseFiles?.length) problems.push(`${s.id}: no licenseFiles`)
    for (const f of s.licenseFiles ?? []) if (!texts.has(f)) problems.push(`${s.id}: license text ${f} is not in licenseTexts`)
  }
  return problems
}

/** The manifest's `sources` (what the in-app credits page shows). */
export function manifestSources(lock) {
  return lock.sources.map((s) => ({
    id: s.id,
    name: s.name,
    version: s.version,
    url: s.homepage,
    license: s.license,
    licenseUrl: s.licenseUrl,
    attribution: s.attribution,
    notes: s.notes,
    changes: s.changes ?? '',
    licenseFiles: (s.licenseFiles ?? []).map((f) => `licenses/${f}`),
  }))
}

function pinLines(s) {
  const out = []
  for (const f of s.files) {
    if (f.url) out.push(`  - ${f.url} (${f.bytes} bytes, SHA-256 ${f.sha256})`)
    else if (f.vendored) out.push(`  - ${f.upstreamUrl} — snapshot ${f.vendored} (${f.bytes} bytes, SHA-256 ${f.sha256})`)
    else if (f.npm) out.push(`  - npm ${f.npm} (${f.bytes} bytes, SHA-256 ${f.sha256})`)
    else if (f.npmDir) out.push(`  - npm ${f.npmDir}: ${f.count} files (tree SHA-256 ${f.treeSha256})`)
    else if (f.local) out.push(`  - ${f.local} (in the repository)`)
  }
  return out
}

/** THIRD_PARTY_NOTICES.md for the licenses/ folder. */
export function thirdPartyNotices(lock, { dataVersion, rows }) {
  const L = []
  L.push('# Third-party notices: dictionary and stroke data')
  L.push('')
  L.push(`Generated by scripts/dict/build.mjs from scripts/dict/sources.lock.json — data version ${dataVersion}. Do not edit by hand.`)
  L.push('')
  L.push("The app's source code is under the MIT License (LICENSE in the repository). None of the licenses below applies to it: the data ships as separate files, each under its own license, listed here.")
  L.push('')
  L.push('## Dictionary: dict/v1/')
  L.push('')
  L.push(
    `The dictionary files (dict/v1/manifest.json and dict/v1/*.tsv, ${rows} entries) are an adaptation of CC-CEDICT, CVDICT and wordfreq, combined with the other sources below, and are licensed under the **Creative Commons Attribution-ShareAlike 4.0 International License** (CC-BY-SA-4.0.txt, https://creativecommons.org/licenses/by-sa/4.0/). They are plain UTF-8 text, neither encrypted nor obfuscated: you may download, share and adapt them under the same license. The row format is documented in scripts/dict/README.md in the repository.`,
  )
  L.push('')
  L.push('What the rows mean for the Vietnamese column (flags column):')
  L.push('')
  L.push('- `mt` — bản dịch máy: machine translation from CVDICT.')
  L.push('- `cur-ai` — hiệu đính bởi AI, chờ duyệt: curated by an AI model (Claude), awaiting human review.')
  L.push('- `cur` — đã hiệu đính: reviewed by a person.')
  L.push('- `en` — chưa có bản dịch: no Vietnamese yet, the CC-CEDICT English senses are shown.')
  L.push(
    '- `hvlow` — the Hán Việt reading has a low-confidence syllable: from Unihan kVietnamese (`hvnom` too: it may be a Nôm reading) or from another pronunciation of the character.',
  )
  L.push(
    '- `hvcur-ai` / `hvcur` — the Hán Việt reading was set by curation (data/overrides/hanviet-word.tsv, hanviet-char.tsv): an AI draft awaiting review, or reviewed by a person.',
  )
  L.push('')
  L.push('## Stroke data: strokes/v2.0.1/')
  L.push('')
  L.push(
    'The stroke files are copied unmodified from hanzi-writer-data 2.0.1 (only renamed to their code point) and are distributed under the Arphic Public License (ARPHICPL.TXT, also in strokes/v2.0.1/). That license covers these data files only.',
  )
  L.push('')
  L.push('## Sources')
  for (const s of lock.sources) {
    L.push('')
    L.push(`### ${s.name}`)
    L.push('')
    L.push(`- Version: ${s.version}`)
    L.push(`- Home: ${s.homepage}`)
    L.push(`- License: ${s.license} — ${s.licenseUrl} (${s.licenseFiles.join(', ')} in this folder)`)
    L.push(`- Attribution: ${s.attribution}`)
    if (s.changes) L.push(`- Changes made: ${s.changes}`)
    if (s.shipped) L.push(`- Shipped as: ${s.shipped}`)
    L.push(`- Ghi chú: ${s.notes}`)
    const pins = pinLines(s)
    if (pins.length) L.push('- Exact input:', ...pins)
  }
  L.push('')
  L.push('## License texts in this folder')
  L.push('')
  for (const t of lock.licenseTexts) L.push(`- ${t.file} — ${t.title}`)
  L.push('')
  return L.join('\n')
}
